spring.application.name=bet-settler

server.port=9000

# Kafka
spring.kafka.bootstrap-servers=192.168.1.12:9092
spring.kafka.consumer.group-id=bet-settler-outcome-consumer
spring.kafka.consumer.auto-offset-reset=earliest

# App topics
app.kafka.topics.event-outcomes=event-outcomes
app.rocketmq.topics.bet-settlements=bet-settlements

# Redis
spring.data.redis.host=192.168.1.12
spring.data.redis.port=6379

logging.level.org.apache.kafka.clients=WARN
